min_version = "2024.9.5"

[tools]
node = "25.4.0"
python = "{{ get_env(name='PYTHON_VERSION', default='3.14') }}"
pre-commit = "latest"


[settings]
lockfile = true

[env]
_.file = [".env.secrets", ".env.local"]

ENV = "dev"
