module.exports = {
	rules: {
		"block-no-empty": true,
		"color-no-invalid-hex": true,
		"declaration-block-no-duplicate-custom-properties": true,
		"declaration-block-no-duplicate-properties": true,
		"font-family-no-duplicate-names": true,
		"function-calc-no-unspaced-operator": true,
		"keyframe-block-no-duplicate-selectors": true,
		"no-duplicate-at-import-rules": true,
		"no-duplicate-selectors": true,
		"no-empty-source": true,
		"no-invalid-double-slash-comments": true,
		"property-no-unknown": true,
		"selector-pseudo-class-no-unknown": true,
		"selector-pseudo-element-no-unknown": true,
		"string-no-newline": true,
		"unit-no-unknown": true,
	},
	ignoreFiles: [
		"node_modules/**/*",
		"public/assets/**/*.css",
		"public/arf.css",
		"public/checkout.css",
		"public/education.css",
		"public/jm/**/*.css",
		"public/theme.css",
		"public/wireframe.css",
		".next/**/*",
		"dist/**/*",
	],
};
