function LogoRow({
	title,
	children,
}: {
	title: string;
	children: React.ReactNode;
}) {
	return (
		<div style={{ marginBottom: 28 }}>
			<h4 style={{ fontWeight: 700, margin: "0 0 8px" }}>{title}</h4>
			<div
				className="skill-tags"
				style={{ display: "flex", flexWrap: "wrap", gap: 8 }}
			>
				{children}
			</div>
		</div>
	);
}

export default function TechnologiesSection() {
	return (
		<section
			className="services-section section-tight-top"
			id="ai-stack"
			aria-labelledby="ai-stack-heading"
		>
			<br />
			<h2 className="section-title" id="ai-stack-heading">
				Technologies & Stack
			</h2>
			<p className="section-subtitle">
				Here is a selection of technologies I use in production.
			</p>
			<div className="services-grid ai-mlops-grid">
				<div className="service-card ai-mlops-wide-card">
					{/* Languages & scripting */}
					<LogoRow title="Languages & scripting">
						<a
							href="https://www.python.org/"
							target="_blank"
							title="Python"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/python-original.svg"
								alt="python"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://www.java.com/"
							target="_blank"
							title="Java"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/java-original.svg"
								alt="java"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://isocpp.org/"
							target="_blank"
							title="C++"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/cplusplus-original.svg"
								alt="c++"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://www.typescriptlang.org/"
							target="_blank"
							title="TypeScript"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/typescript-original.svg"
								alt="typescript"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"
							target="_blank"
							title="JavaScript"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/javascript-original.svg"
								alt="javascript"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://www.gnu.org/software/bash/"
							target="_blank"
							title="Bash"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/gnu_bash-icon.svg"
								alt="bash"
								width="42"
								height="42"
							/>
						</a>
					</LogoRow>
					{/* Web & frontend */}
					<LogoRow title="Web & frontend">
						<a
							href="https://www.w3schools.com/css/"
							target="_blank"
							title="CSS"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/css3-original-wordmark.svg"
								alt="css3"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://www.w3.org/html/"
							target="_blank"
							title="HTML5"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/html5-original-wordmark.svg"
								alt="html5"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://vuejs.org/"
							target="_blank"
							title="Vue.js"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/vuejs-original-wordmark.svg"
								alt="vuejs"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://nuxt.com/"
							target="_blank"
							title="Nuxt.js"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/nuxtjs-icon.svg"
								alt="nuxtjs"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://react.dev/"
							target="_blank"
							title="React"
							rel="noopener"
						>
							<img
								src="https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/react.svg"
								alt="react"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://nodejs.org/"
							target="_blank"
							title="Node.js"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/nodejs-original-wordmark.svg"
								alt="nodejs"
								width="42"
								height="42"
							/>
						</a>
					</LogoRow>
					{/* Cloud, OS & infrastructure */}
					<LogoRow title="Cloud, OS & infrastructure">
						<a
							href="https://aws.amazon.com/"
							target="_blank"
							title="AWS"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/amazonwebservices-original-wordmark.svg"
								alt="aws"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://azure.microsoft.com/"
							target="_blank"
							title="Azure"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/microsoft_azure-icon.svg"
								alt="azure"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://cloud.google.com/"
							target="_blank"
							title="GCP"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/google_cloud-icon.svg"
								alt="gcp"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://www.linux.org/"
							target="_blank"
							title="Linux"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/linux-original.svg"
								alt="linux"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://kubernetes.io/"
							target="_blank"
							title="Kubernetes"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/kubernetes-icon.svg"
								alt="k8s"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://www.nomadproject.io/"
							target="_blank"
							title="Nomad"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/nomad.png"
								alt="nomad"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://www.consul.io/"
							target="_blank"
							title="Consul"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/consul.png"
								alt="consul"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://www.ansible.com/"
							target="_blank"
							title="Ansible"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/ansible-icon.svg"
								alt="ansible"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://www.terraform.io/"
							target="_blank"
							title="Terraform"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/terraformio-icon.svg"
								alt="terraform"
								width="42"
								height="42"
							/>
						</a>
					</LogoRow>
					{/* Security */}
					<LogoRow title="Security">
						<a
							href="https://www.keycloak.org/"
							target="_blank"
							title="Keycloak"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/keycloak.svg"
								alt="keycloak"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://www.vaultproject.io/"
							target="_blank"
							title="Vault"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/vaultproject-icon.svg"
								alt="vault"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://www.zaproxy.org/"
							target="_blank"
							title="OWASP ZAP"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/zap-by-checkmarx.svg"
								alt="zap"
								width="42"
								height="42"
							/>
						</a>
					</LogoRow>
					{/* Databases & messaging */}
					<LogoRow title="Databases, Data & Messaging">
						<a
							href="https://www.postgresql.org/"
							target="_blank"
							title="PostgreSQL"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/postgresql-original-wordmark.svg"
								alt="postgresql"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://www.elastic.co/"
							target="_blank"
							title="Elasticsearch"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/elastic-icon.svg"
								alt="elasticsearch"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://kafka.apache.org/"
							target="_blank"
							title="Kafka"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/apache_kafka-icon.svg"
								alt="kafka"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://mariadb.org/"
							target="_blank"
							title="MariaDB"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/mariadb-icon.svg"
								alt="mariadb"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://www.mongodb.com/"
							target="_blank"
							title="MongoDB"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/mongodb-original-wordmark.svg"
								alt="mongodb"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://www.mysql.com/"
							target="_blank"
							title="MySQL"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/mysql-original-wordmark.svg"
								alt="mysql"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://www.oracle.com/database/"
							target="_blank"
							title="Oracle"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/oracle-original.svg"
								alt="oracle"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://pandas.pydata.org/"
							target="_blank"
							title="Pandas"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/pandas-original.svg"
								alt="pandas"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://redis.io/"
							target="_blank"
							title="Redis"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/redis-original-wordmark.svg"
								alt="redis"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://www.sqlite.org/"
							target="_blank"
							title="SQLite"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/sqlite-icon.svg"
								alt="sqlite"
								width="42"
								height="42"
							/>
						</a>
					</LogoRow>
					{/* DevOps, observability & tooling */}
					<LogoRow title="DevOps, observability & tooling">
						<a
							href="https://git-scm.com/"
							target="_blank"
							title="Git"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/git-scm-icon.svg"
								alt="git"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://grafana.com/"
							target="_blank"
							title="Grafana"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/grafana-icon.svg"
								alt="grafana"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://prometheus.io/"
							target="_blank"
							title="Prometheus"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/prometheusio-icon.svg"
								alt="prometheus"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://grafana.com/oss/loki/"
							target="_blank"
							title="Loki"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/logo-loki.svg"
								alt="loki"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://postman.com/"
							target="_blank"
							title="Postman"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/getpostman-icon.svg"
								alt="postman"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://www.selenium.dev/"
							target="_blank"
							title="Selenium"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/selenium-logo.svg"
								alt="selenium"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://sentry.io/welcome/"
							target="_blank"
							title="Sentry"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/sentryio-icon.svg"
								alt="sentry"
								width="42"
								height="42"
							/>
						</a>
					</LogoRow>
					{/* ML & GPU */}
					<LogoRow title="ML & GPU">
						<a
							href="https://www.nvidia.com/"
							target="_blank"
							title="Nvidia"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/nvidia-icon.svg"
								alt="nvidia"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://pytorch.org/"
							target="_blank"
							title="PyTorch"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/pytorch-icon.svg"
								alt="pytorch"
								width="42"
								height="42"
							/>
						</a>
						{/* Litellm, MCP, langfuse, openai */}
						<a
							href="https://docs.litellm.ai/"
							target="_blank"
							title="Litellm"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/litellm.jpg"
								alt="litellm"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://modelcontextprotocol.io"
							target="_blank"
							title="MCP"
							rel="noopener"
						>
							<img
								src="https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/react.svg"
								alt="mcp"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://langfuse.com/"
							target="_blank"
							title="Langfuse"
							rel="noopener"
						>
							<img
								src="https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/langfuse.png"
								alt="langfuse"
								width="42"
								height="42"
							/>
						</a>
						<a
							href="https://openai.com/"
							target="_blank"
							title="OpenAI"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/openai.svg"
								alt="openai"
								width="42"
								height="42"
							/>
						</a>
					</LogoRow>
					{/* Design */}
					<LogoRow title="Design">
						<a
							href="https://figma.com/"
							target="_blank"
							title="Figma"
							rel="noopener"
						>
							<img
								src="/assets/selfh-icons/figma-icon.svg"
								alt="figma"
								width="42"
								height="42"
							/>
						</a>
					</LogoRow>
				</div>
			</div>
		</section>
	);
}
