// Plain ESM so next.config.mjs can consume the legacy URL compatibility list.
// This is routing infrastructure, not an SEO allowlist; see sitePageCatalog.ts.
export const HTML_ROUTE_SLUGS = [
  "index",
  "contact",
  "ai",
  "security",
  "expertise",
  "workstation",
  "startup",
  "startup-thanks",
  "pricing",
  "success",
  "cancel",
  "payment",
  "ciso",
  "ctid",
  "nabla",
  "login",
  "link",
  "freenas",
  "truenas",
  "test",
  "email",
];
